"""empty message

Revision ID: 502aaad3549c
Revises: 
Create Date: 2023-11-22 02:47:20.952012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502aaad3549c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adninistrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('participante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('juego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.String(length=80), nullable=False),
    sa.Column('imagen', sa.String(length=80), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('finalizado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['adninistrador.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('juego')
    op.drop_table('participante')
    op.drop_table('adninistrador')
    # ### end Alembic commands ###
